-- Drop tables if they exist to ensure a clean slate
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS INSCRIPCION;
DROP TABLE IF EXISTS CURSO;
DROP TABLE IF EXISTS ESTUDIANTE;
DROP TABLE IF EXISTS PROFESOR;
DROP TABLE IF EXISTS PROGRAMA;
DROP TABLE IF EXISTS FACULTAD;
DROP TABLE IF EXISTS PERSONA; 
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE PERSONA (
    ID BIGINT PRIMARY KEY,
    NOMBRES VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255)
);

CREATE TABLE FACULTAD (
    ID BIGINT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL
);
CREATE TABLE FACULTAD (
    ID BIGINT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL
);

CREATE TABLE PROGRAMA (
    ID BIGINT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DURACION DOUBLE,
    REGISTRO_CALIFICADO DATE,
    FACULTAD_ID BIGINT,
    FOREIGN KEY (FACULTAD_ID) REFERENCES FACULTAD(ID)
);

CREATE TABLE ESTUDIANTE (
    ID BIGINT PRIMARY KEY,
    NOMBRES VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    CODIGO BIGINT
);

CREATE TABLE PROFESOR (
    ID BIGINT PRIMARY KEY,
    NOMBRES VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    TIPO_CONTRATO VARCHAR(255)
);

CREATE TABLE CURSO (
    ID BIGINT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    PROGRAMA_ID BIGINT,
    ACTIVO BOOLEAN,
    FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMA(ID)
);

CREATE TABLE INSCRIPCION (
    ID BIGINT PRIMARY KEY,
    ANO INT,
    SEMESTRE INT,
    ESTUDIANTE_ID BIGINT,
    CURSO_ID BIGINT,
    FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTE(ID),
    FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID)
);