-- Create Tables
CREATE TABLE IF NOT EXISTS PERSONA (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS FACULTAD (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DECANO_ID BIGINT,
    FOREIGN KEY (DECANO_ID) REFERENCES PERSONA(ID)
);

CREATE TABLE IF NOT EXISTS PROGRAMA (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    DURACION DOUBLE,
    REGISTRO_CALIFICADO DATE,
    FACULTAD_ID BIGINT,
    FOREIGN KEY (FACULTAD_ID) REFERENCES FACULTAD(ID)
);

CREATE TABLE IF NOT EXISTS ESTUDIANTE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    CODIGO BIGINT
);

CREATE TABLE IF NOT EXISTS PROFESOR (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    TIPO_CONTRATO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CURSO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    PROGRAMA_ID BIGINT,
    ACTIVO BOOLEAN,
    FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMA(ID)
);

CREATE TABLE IF NOT EXISTS INSCRIPCION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ANO INT,
    SEMESTRE INT,
    ESTUDIANTE_ID BIGINT,
    CURSO_ID BIGINT,
    FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTE(ID),
    FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID)
);

CREATE TABLE IF NOT EXISTS CURSOPROFESOR (
    PROFESOR_ID BIGINT,
    CURSO_ID BIGINT,
    ANO INT,
    SEMESTRE INT,
    PRIMARY KEY (PROFESOR_ID, CURSO_ID, ANO, SEMESTRE),
    FOREIGN KEY (PROFESOR_ID) REFERENCES PROFESOR(ID),
    FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID)
);

-- --- DATOS DE EJEMPLO ---

INSERT INTO PERSONA (NOMBRES, APELLIDOS, EMAIL) VALUES ('Ricardo', 'Perez', 'ricardo.perez@university.com');
INSERT INTO PERSONA (NOMBRES, APELLIDOS, EMAIL) VALUES ('Ana', 'Lopez', 'ana.lopez@university.com');
INSERT INTO PERSONA (NOMBRES, APELLIDOS, EMAIL) VALUES ('Luis', 'Martinez', 'luis.martinez@external.com');

INSERT INTO FACULTAD (NOMBRE, DECANO_ID) VALUES ('Ingeniería', 1);
INSERT INTO FACULTAD (NOMBRE, DECANO_ID) VALUES ('Ciencias Sociales', NULL);

INSERT INTO PROGRAMA (NOMBRE, DURACION, REGISTRO_CALIFICADO, FACULTAD_ID) VALUES ('Ingeniería de Sistemas', 10, '2023-01-15', 1);
INSERT INTO PROGRAMA (NOMBRE, DURACION, REGISTRO_CALIFICADO, FACULTAD_ID) VALUES ('Comunicación Social', 8, '2022-05-20', 2);

INSERT INTO PROFESOR (NOMBRES, APELLIDOS, EMAIL, TIPO_CONTRATO) VALUES ('Carlos', 'Ramirez', 'carlos.r@university.com', 'Tiempo Completo');
INSERT INTO PROFESOR (NOMBRES, APELLIDOS, EMAIL, TIPO_CONTRATO) VALUES ('Marta', 'Jimenez', 'marta.j@university.com', 'Cátedra');

INSERT INTO ESTUDIANTE (NOMBRES, APELLIDOS, EMAIL, CODIGO) VALUES ('Juan', 'Gomez', 'juan.g@student.com', 20241001);
INSERT INTO ESTUDIANTE (NOMBRES, APELLIDOS, EMAIL, CODIGO) VALUES ('Maria', 'Rodriguez', 'maria.r@student.com', 20241002);

INSERT INTO CURSO (NOMBRE, PROGRAMA_ID, ACTIVO) VALUES ('Cálculo Diferencial', 1, TRUE);
INSERT INTO CURSO (NOMBRE, PROGRAMA_ID, ACTIVO) VALUES ('Programación Orientada a Objetos', 1, TRUE);
INSERT INTO CURSO (NOMBRE, PROGRAMA_ID, ACTIVO) VALUES ('Teorías de la Comunicación', 2, FALSE);

INSERT INTO CURSOPROFESOR (PROFESOR_ID, CURSO_ID, ANO, SEMESTRE) VALUES (1, 1, 2025, 1);
INSERT INTO CURSOPROFESOR (PROFESOR_ID, CURSO_ID, ANO, SEMESTRE) VALUES (2, 2, 2025, 1);

INSERT INTO INSCRIPCION (ESTUDIANTE_ID, CURSO_ID, ANO, SEMESTRE) VALUES (1, 1, 2025, 1);
INSERT INTO INSCRIPCION (ESTUDIANTE_ID, CURSO_ID, ANO, SEMESTRE) VALUES (2, 2, 2025, 1);