-- Eliminar tablas si existen (ignorar errores si no existen)
DROP TABLE INSCRIPCION;
DROP TABLE CURSO;
DROP TABLE PROFESOR;
DROP TABLE ESTUDIANTE;
DROP TABLE PROGRAMA;
DROP TABLE FACULTAD;

-- Crear tablas con los tipos de datos correctos para Oracle
CREATE TABLE FACULTAD (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(255) NOT NULL
);

CREATE TABLE PROGRAMA (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(255) NOT NULL,
    DURACION NUMBER,
    REGISTRO_CALIFICADO DATE,
    FACULTAD_ID NUMBER,
    CONSTRAINT FK_PROG_FACULTAD FOREIGN KEY (FACULTAD_ID) REFERENCES FACULTAD(ID)
);

CREATE TABLE ESTUDIANTE (
    ID NUMBER PRIMARY KEY,
    NOMBRES VARCHAR2(255) NOT NULL,
    APELLIDOS VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255),
    CODIGO NUMBER
);

CREATE TABLE PROFESOR (
    ID NUMBER PRIMARY KEY,
    NOMBRES VARCHAR2(255) NOT NULL,
    APELLIDOS VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255),
    TIPO_CONTRATO VARCHAR2(255)
);

CREATE TABLE CURSO (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(255) NOT NULL,
    PROGRAMA_ID NUMBER,
    ACTIVO NUMBER(1),
    CONSTRAINT FK_CURSO_PROG FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMA(ID)
);

CREATE TABLE INSCRIPCION (
    ID NUMBER PRIMARY KEY,
    ANO NUMBER,
    SEMESTRE NUMBER,
    ESTUDIANTE_ID NUMBER,
    CURSO_ID NUMBER,
    CONSTRAINT FK_INSC_ESTUD FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTE(ID),
    CONSTRAINT FK_INSC_CURSO FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID)
);